import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async rewrites() {
    return [
      // App Router segments cannot begin with a dot, so the Apple app site
      // association file is generated by a normally named route.
      { source: "/.well-known/apple-app-site-association", destination: "/api/apple-app-site-association" },
    ];
  },
};

export default nextConfig;
