"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { SUPPORTED_COUNTRY_CODES } from "@/lib/regions";
import { LANGUAGE_LABEL_KEYS, translate, UI_LANGUAGES, type UiLanguage } from "@/ios/i18n";
import { useUiText } from "@/components/useUiText";

export default function OnboardingPage() {
  const { authenticated, authHeaders, loading } = useAuth();
  const t = useUiText();
  const [name, setName] = useState(""); const [countryCode, setCountryCode] = useState(""); const [language, setLanguage] = useState(""); const [handle, setHandle] = useState(""); const [cuisines, setCuisines] = useState(""); const [avatar, setAvatar] = useState<File | null>(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!loading && !authenticated) window.location.replace("/auth/login?next=/onboarding"); }, [authenticated, loading]);
  useEffect(() => { if (!authenticated) return; void fetch("/api/onboarding", { headers: authHeaders(), cache: "no-store" }).then(async (response) => response.ok ? response.json() as Promise<{ complete: boolean }> : null).then((result) => { if (result?.complete) window.location.replace("/"); }); }, [authHeaders, authenticated]);
  function selectAvatar(event: ChangeEvent<HTMLInputElement>) { setAvatar(event.target.files?.[0] ?? null); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setStatus(""); if (!name.trim() || !handle.trim() || !countryCode || !language) { setStatus(t("publish.requirements")); setBusy(false); return; } try { const response = await fetch("/api/onboarding", { method: "PUT", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ name, countryCode, language, handle, favoriteCuisines: cuisines.split(",") }) }); if (!response.ok) { setStatus(t("onboarding.saveFailed")); return; } if (avatar) { const data = new FormData(); data.set("file", avatar); const imageResponse = await fetch("/api/profile/avatar", { method: "POST", headers: authHeaders(), body: data }); if (!imageResponse.ok) { setStatus(t("onboarding.photoFailed")); return; } } window.location.replace("/"); } finally { setBusy(false); } }
  const countryNames = new Intl.DisplayNames([language || "en"], { type: "region" });
  if (loading || !authenticated) return <main><p>{t("onboarding.loading")}</p></main>;
  return <main className="auth-page"><section className="account-card"><h1>{t("onboarding.title")}</h1><p>{t("onboarding.help")}</p><form onSubmit={submit}><label>{t("onboarding.name")}<input value={name} onChange={(event) => setName(event.target.value)} maxLength={80} required /></label><label>{t("onboarding.username")}<input value={handle} onChange={(event) => setHandle(event.target.value.toLowerCase())} minLength={3} maxLength={30} required /></label><label>{t("onboarding.country")}<select value={countryCode} onChange={(event) => setCountryCode(event.target.value)} required><option value="" disabled>{t("onboarding.chooseCountry")}</option>{SUPPORTED_COUNTRY_CODES.map((code) => <option key={code} value={code}>{countryNames.of(code) ?? code}</option>)}</select></label><label>{t("onboarding.language")}<select value={language} onChange={(event) => setLanguage(event.target.value as UiLanguage)} required><option value="" disabled>{t("onboarding.chooseLanguage")}</option>{UI_LANGUAGES.map((item) => <option key={item} value={item}>{translate(language || "en", LANGUAGE_LABEL_KEYS[item])}</option>)}</select></label><label>{t("onboarding.cuisines")}<input value={cuisines} onChange={(event) => setCuisines(event.target.value)} placeholder={t("onboarding.cuisineExample")} /></label><label>{t("onboarding.photo")}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={selectAvatar} /></label><button className="primary" disabled={busy}>{busy ? t("onboarding.saving") : t("onboarding.save")}</button>{status && <p role="status">{status}</p>}</form></section></main>;
}
