import type { NormalizedLocation } from "./location.ts";

/** Representative validation fixtures only; runtime location support remains country/coordinate based. */
export const PILOT_ANCHORS: ReadonlyArray<NormalizedLocation & { id: string; label: string }> = [
  { id: "us-new-york", label: "New York", latitude: 40.7128, longitude: -74.006, locality: "New York", administrativeRegion: "NY", countryCode: "US", timeZone: "America/New_York", currencyCode: "USD", locale: "en-US", language: "en-US", measurementSystem: "imperial", source: "manual" },
  { id: "us-los-angeles", label: "Los Angeles", latitude: 34.0522, longitude: -118.2437, locality: "Los Angeles", administrativeRegion: "CA", countryCode: "US", timeZone: "America/Los_Angeles", currencyCode: "USD", locale: "en-US", language: "en-US", measurementSystem: "imperial", source: "manual" },
  { id: "us-austin", label: "Austin", latitude: 30.2672, longitude: -97.7431, locality: "Austin", administrativeRegion: "TX", countryCode: "US", timeZone: "America/Chicago", currencyCode: "USD", locale: "en-US", language: "en-US", measurementSystem: "imperial", source: "manual" },
  { id: "ca-vancouver", label: "Vancouver", latitude: 49.2827, longitude: -123.1207, locality: "Vancouver", administrativeRegion: "BC", countryCode: "CA", timeZone: "America/Vancouver", currencyCode: "CAD", locale: "en-CA", language: "en-CA", measurementSystem: "metric", source: "manual" },
  { id: "ca-toronto", label: "Toronto", latitude: 43.6532, longitude: -79.3832, locality: "Toronto", administrativeRegion: "ON", countryCode: "CA", timeZone: "America/Toronto", currencyCode: "CAD", locale: "en-CA", language: "en-CA", measurementSystem: "metric", source: "manual" },
  { id: "ca-montreal", label: "Montreal", latitude: 45.5019, longitude: -73.5674, locality: "Montréal", administrativeRegion: "QC", countryCode: "CA", timeZone: "America/Toronto", currencyCode: "CAD", locale: "fr-CA", language: "fr", measurementSystem: "metric", source: "manual" },
  { id: "mx-mexico-city", label: "Mexico City", latitude: 19.4326, longitude: -99.1332, locality: "Ciudad de México", administrativeRegion: "CMX", countryCode: "MX", timeZone: "America/Mexico_City", currencyCode: "MXN", locale: "es-MX", language: "es", measurementSystem: "metric", source: "manual" },
  { id: "mx-guadalajara", label: "Guadalajara", latitude: 20.6597, longitude: -103.3496, locality: "Guadalajara", administrativeRegion: "JAL", countryCode: "MX", timeZone: "America/Mexico_City", currencyCode: "MXN", locale: "es-MX", language: "es", measurementSystem: "metric", source: "manual" },
  { id: "mx-monterrey", label: "Monterrey", latitude: 25.6866, longitude: -100.3161, locality: "Monterrey", administrativeRegion: "NLE", countryCode: "MX", timeZone: "America/Monterrey", currencyCode: "MXN", locale: "es-MX", language: "es", measurementSystem: "metric", source: "manual" },
  { id: "gb-london", label: "London", latitude: 51.5074, longitude: -0.1278, locality: "London", administrativeRegion: "England", countryCode: "GB", timeZone: "Europe/London", currencyCode: "GBP", locale: "en-GB", language: "en-GB", measurementSystem: "imperial", source: "manual" },
  { id: "gb-manchester", label: "Manchester", latitude: 53.4808, longitude: -2.2426, locality: "Manchester", administrativeRegion: "England", countryCode: "GB", timeZone: "Europe/London", currencyCode: "GBP", locale: "en-GB", language: "en-GB", measurementSystem: "imperial", source: "manual" },
  { id: "gb-edinburgh", label: "Edinburgh", latitude: 55.9533, longitude: -3.1883, locality: "Edinburgh", administrativeRegion: "Scotland", countryCode: "GB", timeZone: "Europe/London", currencyCode: "GBP", locale: "en-GB", language: "en-GB", measurementSystem: "imperial", source: "manual" },
  { id: "fr-paris", label: "Paris", latitude: 48.8566, longitude: 2.3522, locality: "Paris", administrativeRegion: "Île-de-France", countryCode: "FR", timeZone: "Europe/Paris", currencyCode: "EUR", locale: "fr-FR", language: "fr", measurementSystem: "metric", source: "manual" },
  { id: "fr-lyon", label: "Lyon", latitude: 45.764, longitude: 4.8357, locality: "Lyon", administrativeRegion: "Auvergne-Rhône-Alpes", countryCode: "FR", timeZone: "Europe/Paris", currencyCode: "EUR", locale: "fr-FR", language: "fr", measurementSystem: "metric", source: "manual" },
  { id: "fr-marseille", label: "Marseille", latitude: 43.2965, longitude: 5.3698, locality: "Marseille", administrativeRegion: "Provence-Alpes-Côte d'Azur", countryCode: "FR", timeZone: "Europe/Paris", currencyCode: "EUR", locale: "fr-FR", language: "fr", measurementSystem: "metric", source: "manual" },
];
